import mongoose from 'mongoose';

const ShortcutKeySchema = new mongoose.Schema({
    keystroke: { type: String, required: true },
    feature: { type: String, required: true },
    code: { type: Number, required: true },
    shortCutType: {
        type: String,
        enum: ['global', 'page', 'subPage'],
        default: 'global',
    }, // 1- global , 2- page, 3- subPage
    isDefault: { type: Boolean, default: true },
    isEditable: { type: Boolean, default: false },
    createdBy: [
        {
            userId: { type: String },
            userName: { type: String },
            profilePic: { type: String },
        },
    ],
    updatedBy: [
        {
            userId: { type: String },
            userName: { type: String },
            profilePic: { type: String },
        },
    ],
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now },
});

let shortcutKeyModel= mongoose.model('shortcutKeys', ShortcutKeySchema);
export default shortcutKeyModel;

export let shortcutKey = [
    //reset data
    {
        keystroke: 'CTRL + O',
        feature: 'Reset All Data',
        code: 80,
        shortCutType: 'global',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    //dashboard
    {
        keystroke: 'CTRL + D',
        feature: 'View Dashboard',
        code: 90,
        shortCutType: 'global',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    //project
    {
        keystroke: 'CTRL + P',
        feature: 'View All Project',
        code: 100,
        shortCutType: 'global',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + G',
        feature: 'Create Project page',
        code: 101,
        shortCutType: 'global',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + SHIFT + M',
        feature: 'Create Project Modal',
        code: 102,
        shortCutType: 'page',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + SHIFT + F',
        feature: 'View Project Filter',
        code: 103,
        shortCutType: 'page',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + SHIFT + T',
        feature: 'View Project Table Filter',
        code: 104,
        shortCutType: 'page',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + SHIFT + DEL',
        feature: 'Delete All Project',
        code: 105,
        shortCutType: 'page',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + SHIFT + D',
        feature: 'Download All Project',
        code: 106,
        shortCutType: 'page',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    //task
    {
        keystroke: 'CTRL + T',
        feature: 'View All Task',
        code: 200,
        shortCutType: 'global',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + C ',
        feature: 'Create Task page',
        code: 201,
        shortCutType: 'global',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + SHIFT + C',
        feature: 'Create Task Modal',
        code: 202,
        shortCutType: 'page',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + K',
        feature: 'Review Task',
        code: 203,
        shortCutType: 'global',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + SHIFT + V',
        feature: 'View Task Filter',
        code: 204,
        shortCutType: 'page',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + SHIFT + R',
        feature: 'View Task Table Filter',
        code: 205,
        shortCutType: 'page',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + SHIFT + X',
        feature: 'Delete All Task',
        code: 206,
        shortCutType: 'page',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + SHIFT + S',
        feature: 'Download All Task',
        code: 207,
        shortCutType: 'page',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    //member
    {
        keystroke: 'CTRL + M',
        feature: 'View All Member',
        code: 300,
        shortCutType: 'global',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + SHIFT + I',
        feature: 'Add Single Member',
        code: 301,
        shortCutType: 'page',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + SHIFT + B',
        feature: 'Add Bulk Member',
        code: 302,
        shortCutType: 'page',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + SHIFT + Q',
        feature: 'View Member Filter',
        code: 303,
        shortCutType: 'page',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + SHIFT + Z',
        feature: 'View Member Table Filter',
        code: 304,
        shortCutType: 'page',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + SHIFT + L',
        feature: 'Delete All Member',
        code: 305,
        shortCutType: 'page',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + SHIFT + G',
        feature: 'Download All Member',
        code: 306,
        shortCutType: 'page',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    //role
    {
        keystroke: 'CTRL + R',
        feature: 'View All Roles',
        code: 400,
        shortCutType: 'global',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + DEL',
        feature: 'Delete All Roles',
        code: 401,
        shortCutType: 'global',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    //config
    {
        keystroke: 'CTRL + V',
        feature: 'View Task Configuration',
        code: 500,
        shortCutType: 'global',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + Z',
        feature: 'Download Task Category Configuration',
        code: 501,
        shortCutType: 'global',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'SHIFT + ALT + DEL',
        feature: 'Delete All Task Category Configuration',
        code: 502,
        shortCutType: 'subPage',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + S',
        feature: 'Download Task Status Configuration',
        code: 503,
        shortCutType: 'global',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'SHIFT + ALT + S',
        feature: 'Delete All  Task Status Configuration',
        code: 504,
        shortCutType: 'subPage',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + H',
        feature: 'Download Task type Configuration',
        code: 505,
        shortCutType: 'global',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'SHIFT + ALT + T',
        feature: 'Delete All  Task type Configuration',
        code: 506,
        shortCutType: 'subPage',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'CTRL + A',
        feature: 'Download Task Stages Configuration',
        code: 507,
        shortCutType: 'global',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
    {
        keystroke: 'SHIFT + ALT + C',
        feature: 'Delete All Task Stages Configuration',
        code: 508,
        shortCutType: 'subPage',
        isDefault: true,
        isEditable: false,
        created_By: [],
        updated_By: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
    },
];
