import { downloadFiles } from './download';
export const isRequiredErrorMessage = 'is required';
export const adminProfilePic = 'test';
export const currencyType = 'INR';
export const OrgId = 'GLB-BAN-100';
export const roleList = [
    { text: 'Member', name: 'Member', value: 'Member' },
    { text: 'Manager', name: 'Manager', value: 'Manager' },
    { text: 'Sponsor', name: 'Sponsor', value: 'Sponsor' },
    { text: 'Owner', name: 'Owner', value: 'Owner' },
    { text: 'Client', name: 'Client', value: 'Client' },
];
export const priorityList = [
    { name: 'High', value: 'High' },
    { name: 'Medium', value: 'Medium' },
    { name: 'Low', value: 'Low' },
];
export const usersDummyData = [
    {
        value: {
            id: 'GLB-102',
            email: 'neetu@gmail.com',
            fullName: 'shraddha',
            profilePic: 'abc.pneg',
        },
        key: 'shraddha',
    },
    {
        value: {
            id: 'GLB-102',
            email: 'neetu@gmail.com',
            fullName: 'abhishek',
            profilePic: 'abc.pneg',
        },
        key: 'abhishek',
    },
];
export const usersProjectDummyData = [
    {
        value: {
            id: 'GLB-106',
            orgId: 'GLB-BAN-0066',
            firstName: 'Karamveer',
            lastName: 'Babu',
            email: 'Karamveer@empmonitor.com',
            role: 'Software Developer',
            verified: true,
            profilePic: 'piyush.pneg',
        },
        key: 'Karamveer babu',
    },
    {
        value: {
            id: 'GLB-105',
            orgId: 'GLB-BAN-006',
            firstName: 'Suresh',
            lastName: 'Babu',
            email: 'sureshbabu@empmonitor.com',
            role: 'Software Developer',
            verified: true,
            profilePic: 'piyush.pneg',
        },
        key: 'Suresh babu',
    },
    {
        value: {
            id: 'GLB-101',
            orgId: 'GLB-BAN-001',
            firstName: 'piyush',
            lastName: 'patel',
            email: 'piyush@empmonitor.com',
            role: 'Software Developer',
            verified: true,
            profilePic: 'piyush.pneg',
        },
        key: 'piyush Kumar',
    },
    {
        value: {
            id: 'GLB-102',
            orgId: 'GLB-BAN-001',
            firstName: 'p',
            lastName: 'k',
            email: 'neetu@empmonitor.com',
            role: 'Software Developer',
            verified: true,
            profilePic: 'neetu.pneg',
        },
        key: 'neetu patel',
    },
];
export const taskTableList = [
    { name: 'Projects', key: 1 },
    { name: 'Description', key: 2 },
    { name: 'Created', key: 3 },
    { name: 'Created by', key: 4 },
    { name: 'Owner', key: 5 },
    { name: 'Client', key: 6 },
    { name: 'Planned Budget', key: 7 },
    { name: 'Actual Budget', key: 8 },
    { name: 'Assigned To', key: 9 },
    { name: 'Action', key: 10 },
];
export const stageList = [
    { text: 'Default', value: 'Default' },
    { text: 'Initiation', value: 'Initiation' },
    { text: 'Development', value: 'Development' },
    { text: 'Local', value: 'Local' },
    { text: 'Planning', value: 'Planning' },
    { text: 'Execution', value: 'Execution' },
    { text: 'New Feature', value: 'New Feature' },
    { text: 'Monitoring and control', value: 'Monitoring and control' },
    { text: 'Closure', value: 'Closure' },
];
export const categoryList = [
    { text: 'Default', value: 'Default' },
    { text: 'Problem ticket', value: 'Problem ticket' },
    { text: 'Incident', value: 'Incident' },
    { text: 'Service Request', value: 'Service Request' },
];
export const currencyList = [
    { text: '₹ Indian Rupee', value: 'INR' },
    { text: '$ US Dollar', value: 'USD' },
    { text: "€ Euro", value: "EUR" },
    { text: '£ British Pound', value: 'GBP' },
    { text: '¥ Japanese Yen', value: 'JPY' },
    { text: '€ CHF Swiss Franc', value: 'CHF' },
    { text: '$ AUD Australian Dollar', value: 'AUD' },
    { text: '$ CAD Canadian Dollar', value: 'CAD' },
    { text: '¥ CNY Chinese Yuan', value: 'CNY' },
    { text: '₩ KRW South Korean Won', value: 'KRW' },
    { text: '₦ Naira', value: 'NGN' },

]
export const download_data = [
    {
        text: 'Download CSV file',
        value: 'excel',
        onClick: (event, value, data, name) => {
            downloadFiles(value, name, data);
        },
    },
    {
        text: 'Download PDF file',
        value: 'pdf',
        onClick: (event, value, data, name) => {
            downloadFiles(value, name, data);
        },
    },
];
export const workForce = [
    { text: '1-10 Users', value: 10 },
    { text: '11-50 Users', value: 50 },
    { text: '51-200 Users', value: 200 },
    { text: '200+ Users', value: 201 },
];
export const country_data = [
    { value: 'India', text: 'India' },
    { value: 'Algeria', text: 'Algeria' },
    { value: 'Albania', text: 'Albania' },
    { value: 'Afghanistan', text: 'Afghanistan' },
    { value: 'other', text: 'Other' },
];
export const COUNTRIES = [
    {
        text: 'Afghanistan',
        value: 'AF',
        timezone: 'Afghanistan Standard Time',
        utc: 'UTC+04:30',
        mobileCode: '+93',
    },
    {
        text: 'Åland Islands',
        value: 'AX',
        timezone: 'FLE Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+358-18',
    },
    {
        text: 'Albania',
        value: 'AL',
        timezone: 'Central Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+355',
    },
    {
        text: 'Algeria',
        value: 'DZ',
        timezone: 'W. Central Africa Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+213',
    },
    {
        text: 'American Samoa',
        value: 'AS',
        timezone: 'UTC-11',
        utc: 'UTC-11:00',
        mobileCode: '+1-684',
    },
    {
        text: 'Andorra',
        value: 'AD',
        timezone: 'W. Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+376',
    },
    {
        text: 'Angola',
        value: 'AO',
        timezone: 'W. Central Africa Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+244',
    },
    {
        text: 'Anguilla',
        value: 'AI',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+1-264',
    },
    {
        text: 'Antarctica',
        value: 'AQ',
        timezone: 'Pacific SA Standard Time',
        utc: 'UTC-03:00',
        mobileCode: '+',
    },
    {
        text: 'Antigua and Barbuda',
        value: 'AG',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+1-268',
    },
    {
        text: 'Argentina',
        value: 'AR',
        timezone: 'Argentina Standard Time',
        utc: 'UTC-03:00',
        mobileCode: '+54',
    },
    {
        text: 'Armenia',
        value: 'AM',
        timezone: 'Caucasus Standard Time',
        utc: 'UTC+04:00',
        mobileCode: '+374',
    },
    {
        text: 'Aruba',
        value: 'AW',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+297',
    },
    {
        text: 'Australia',
        value: 'AU',
        timezone: 'AUS Eastern Standard Time',
        utc: 'UTC+10:00',
        mobileCode: '+61',
    },
    {
        text: 'Austria',
        value: 'AT',
        timezone: 'W. Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+43',
    },
    {
        text: 'Azerbaijan',
        value: 'AZ',
        timezone: 'Azerbaijan Standard Time',
        utc: 'UTC+04:00',
        mobileCode: '+994',
    },
    {
        text: 'Bahamas, The',
        value: 'BS',
        timezone: 'Eastern Standard Time',
        utc: 'UTC-05:00',
        mobileCode: '+1-242',
    },
    {
        text: 'Bahrain',
        value: 'BH',
        timezone: 'Arab Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+973',
    },
    {
        text: 'Bangladesh',
        value: 'BD',
        timezone: 'Bangladesh Standard Time',
        utc: 'UTC+06:00',
        mobileCode: '+880',
    },
    {
        text: 'Barbados',
        value: 'BB',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+1-246',
    },
    {
        text: 'Belarus',
        value: 'BY',
        timezone: 'Belarus Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+375',
    },
    {
        text: 'Belgium',
        value: 'BE',
        timezone: 'Romance Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+32',
    },
    {
        text: 'Belize',
        value: 'BZ',
        timezone: 'Central America Standard Time',
        utc: 'UTC-06:00',
        mobileCode: '+501',
    },
    {
        text: 'Benin',
        value: 'BJ',
        timezone: 'W. Central Africa Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+229',
    },
    {
        text: 'Bermuda',
        value: 'BM',
        timezone: 'Atlantic Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+1-441',
    },
    {
        text: 'Bhutan',
        value: 'BT',
        timezone: 'Bangladesh Standard Time',
        utc: 'UTC+06:00',
        mobileCode: '+975',
    },
    {
        text: 'Bolivarian Republic of Venezuela',
        value: 'VE',
        timezone: 'Venezuela Standard Time',
        utc: 'UTC-04:30',
        mobileCode: '+58',
    },
    {
        text: 'Bolivia',
        value: 'BO',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+591',
    },
    {
        text: 'Bonaire, Sint Eustatius and Saba',
        value: 'BQ',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+599',
    },
    {
        text: 'Bosnia and Herzegovina',
        value: 'BA',
        timezone: 'Central European Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+387',
    },
    {
        text: 'Botswana',
        value: 'BW',
        timezone: 'South Africa Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+267',
    },
    {
        text: 'Bouvet Island',
        value: 'BV',
        timezone: 'UTC',
        utc: 'UTC',
        mobileCode: '+',
    },
    {
        text: 'Brazil',
        value: 'BR',
        timezone: 'E. South America Standard Time',
        utc: 'UTC-03:00',
        mobileCode: '+55',
    },
    {
        text: 'British Indian Ocean Territory',
        value: 'IO',
        timezone: 'Central Asia Standard Time',
        utc: 'UTC+06:00',
        mobileCode: '+246',
    },
    {
        text: 'Brunei',
        value: 'BN',
        timezone: 'Singapore Standard Time',
        utc: 'UTC+08:00',
        mobileCode: '+673',
    },
    {
        text: 'Bulgaria',
        value: 'BG',
        timezone: 'FLE Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+359',
    },
    {
        text: 'Burkina Faso',
        value: 'BF',
        timezone: 'Greenwich Standard Time',
        utc: 'UTC',
        mobileCode: '+226',
    },
    {
        text: 'Burundi',
        value: 'BI',
        timezone: 'South Africa Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+257',
    },
    {
        text: 'Cabo Verde',
        value: 'CV',
        timezone: 'Cape Verde Standard Time',
        utc: 'UTC-01:00',
        mobileCode: '+238',
    },
    {
        text: 'Cambodia',
        value: 'KH',
        timezone: 'SE Asia Standard Time',
        utc: 'UTC+07:00',
        mobileCode: '+855',
    },
    {
        text: 'Cameroon',
        value: 'CM',
        timezone: 'W. Central Africa Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+237',
    },
    {
        text: 'Canada',
        value: 'CA',
        timezone: 'Eastern Standard Time',
        utc: 'UTC-05:00',
        mobileCode: '+1',
    },
    {
        text: 'Cayman Islands',
        value: 'KY',
        timezone: 'SA Pacific Standard Time',
        utc: 'UTC-05:00',
        mobileCode: '+1-345',
    },
    {
        text: 'Central African Republic',
        value: 'CF',
        timezone: 'W. Central Africa Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+236',
    },
    {
        text: 'Chad',
        value: 'TD',
        timezone: 'W. Central Africa Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+235',
    },
    {
        text: 'Chile',
        value: 'CL',
        timezone: 'Pacific SA Standard Time',
        utc: 'UTC-03:00',
        mobileCode: '+56',
    },
    {
        text: 'China',
        value: 'CN',
        timezone: 'China Standard Time',
        utc: 'UTC+08:00',
        mobileCode: '+86',
    },
    {
        text: 'Christmas Island',
        value: 'CX',
        timezone: 'SE Asia Standard Time',
        utc: 'UTC+07:00',
        mobileCode: '+61',
    },
    {
        text: 'Cocos (Keeling) Islands',
        value: 'CC',
        timezone: 'Myanmar Standard Time',
        utc: 'UTC+06:30',
        mobileCode: '+61',
    },
    {
        text: 'Colombia',
        value: 'CO',
        timezone: 'SA Pacific Standard Time',
        utc: 'UTC-05:00',
        mobileCode: '+57',
    },
    {
        text: 'Comoros',
        value: 'KM',
        timezone: 'E. Africa Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+269',
    },
    {
        text: 'Congo',
        value: 'CG',
        timezone: 'W. Central Africa Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+242',
    },
    {
        text: 'Congo (DRC)',
        value: 'CD',
        timezone: 'W. Central Africa Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+243',
    },
    {
        text: 'Cook Islands',
        value: 'CK',
        timezone: 'Hawaiian Standard Time',
        utc: 'UTC-10:00',
        mobileCode: '+682',
    },
    {
        text: 'Costa Rica',
        value: 'CR',
        timezone: 'Central America Standard Time',
        utc: 'UTC-06:00',
        mobileCode: '+506',
    },
    {
        text: "Côte d'Ivoire",
        value: 'CI',
        timezone: 'Greenwich Standard Time',
        utc: 'UTC',
        mobileCode: '+225',
    },
    {
        text: 'Croatia',
        value: 'HR',
        timezone: 'Central European Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+385',
    },
    {
        text: 'Cuba',
        value: 'CU',
        timezone: 'Eastern Standard Time',
        utc: 'UTC-05:00',
        mobileCode: '+53',
    },
    {
        text: 'Curaçao',
        value: 'CW',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+599',
    },
    {
        text: 'Cyprus',
        value: 'CY',
        timezone: 'E. Europe Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+357',
    },
    {
        text: 'Czech Republic',
        value: 'CZ',
        timezone: 'Central Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+420',
    },
    {
        text: 'Democratic Republic of Timor-Leste',
        value: 'TL',
        timezone: 'Tokyo Standard Time',
        utc: 'UTC+09:00',
        mobileCode: '+670',
    },
    {
        text: 'Denmark',
        value: 'DK',
        timezone: 'Romance Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+45',
    },
    {
        text: 'Djibouti',
        value: 'DJ',
        timezone: 'E. Africa Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+253',
    },
    {
        text: 'Dominica',
        value: 'DM',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+1-767',
    },
    {
        text: 'Dominican Republic',
        value: 'DO',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+1-809 and 1-829',
    },
    {
        text: 'Ecuador',
        value: 'EC',
        timezone: 'SA Pacific Standard Time',
        utc: 'UTC-05:00',
        mobileCode: '+593',
    },
    {
        text: 'Egypt',
        value: 'EG',
        timezone: 'Egypt Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+20',
    },
    {
        text: 'El Salvador',
        value: 'SV',
        timezone: 'Central America Standard Time',
        utc: 'UTC-06:00',
        mobileCode: '+503',
    },
    {
        text: 'Equatorial Guinea',
        value: 'GQ',
        timezone: 'W. Central Africa Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+240',
    },
    {
        text: 'Eritrea',
        value: 'ER',
        timezone: 'E. Africa Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+291',
    },
    {
        text: 'Estonia',
        value: 'EE',
        timezone: 'FLE Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+372',
    },
    {
        text: 'Ethiopia',
        value: 'ET',
        timezone: 'E. Africa Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+251',
    },
    {
        text: 'Falkland Islands (Islas Malvinas)',
        value: 'FK',
        timezone: 'SA Eastern Standard Time',
        utc: 'UTC-03:00',
        mobileCode: '+500',
    },
    {
        text: 'Faroe Islands',
        value: 'FO',
        timezone: 'GMT Standard Time',
        utc: 'UTC',
        mobileCode: '+298',
    },
    {
        text: 'Fiji Islands',
        value: 'FJ',
        timezone: 'Fiji Standard Time',
        utc: 'UTC+12:00',
        mobileCode: '+679',
    },
    {
        text: 'Finland',
        value: 'FI',
        timezone: 'FLE Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+358',
    },
    {
        text: 'France',
        value: 'FR',
        timezone: 'Romance Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+33',
    },
    {
        text: 'French Guiana',
        value: 'GF',
        timezone: 'SA Eastern Standard Time',
        utc: 'UTC-03:00',
        mobileCode: '+594',
    },
    {
        text: 'French Polynesia',
        value: 'PF',
        timezone: 'Hawaiian Standard Time',
        utc: 'UTC-10:00',
        mobileCode: '+689',
    },
    {
        text: 'French Southern and Antarctic Lands',
        value: 'TF',
        timezone: 'West Asia Standard Time',
        utc: 'UTC+05:00',
        mobileCode: '+',
    },
    {
        text: 'Gabon',
        value: 'GA',
        timezone: 'W. Central Africa Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+241',
    },
    {
        text: 'Gambia, The',
        value: 'GM',
        timezone: 'Greenwich Standard Time',
        utc: 'UTC',
        mobileCode: '+220',
    },
    {
        text: 'Georgia',
        value: 'GE',
        timezone: 'Georgian Standard Time',
        utc: 'UTC+04:00',
        mobileCode: '+995',
    },
    {
        text: 'Germany',
        value: 'DE',
        timezone: 'W. Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+49',
    },
    {
        text: 'Ghana',
        value: 'GH',
        timezone: 'Greenwich Standard Time',
        utc: 'UTC',
        mobileCode: '+233',
    },
    {
        text: 'Gibraltar',
        value: 'GI',
        timezone: 'W. Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+350',
    },
    {
        text: 'Greece',
        value: 'GR',
        timezone: 'GTB Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+30',
    },
    {
        text: 'Greenland',
        value: 'GL',
        timezone: 'Greenland Standard Time',
        utc: 'UTC-03:00',
        mobileCode: '+299',
    },
    {
        text: 'Grenada',
        value: 'GD',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+1-473',
    },
    {
        text: 'Guadeloupe',
        value: 'GP',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+590',
    },
    {
        text: 'Guam',
        value: 'GU',
        timezone: 'West Pacific Standard Time',
        utc: 'UTC+10:00',
        mobileCode: '+1-671',
    },
    {
        text: 'Guatemala',
        value: 'GT',
        timezone: 'Central America Standard Time',
        utc: 'UTC-06:00',
        mobileCode: '+502',
    },
    {
        text: 'Guernsey',
        value: 'GG',
        timezone: 'GMT Standard Time',
        utc: 'UTC',
        mobileCode: '+44-1481',
    },
    {
        text: 'Guinea',
        value: 'GN',
        timezone: 'Greenwich Standard Time',
        utc: 'UTC',
        mobileCode: '+224',
    },
    {
        text: 'Guinea-Bissau',
        value: 'GW',
        timezone: 'Greenwich Standard Time',
        utc: 'UTC',
        mobileCode: '+245',
    },
    {
        text: 'Guyana',
        value: 'GY',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+592',
    },
    {
        text: 'Haiti',
        value: 'HT',
        timezone: 'Eastern Standard Time',
        utc: 'UTC-05:00',
        mobileCode: '+509',
    },
    {
        text: 'Heard Island and McDonald Islands',
        value: 'HM',
        timezone: 'Mauritius Standard Time',
        utc: 'UTC+04:00',
        mobileCode: '+ ',
    },
    {
        text: 'Honduras',
        value: 'HN',
        timezone: 'Central America Standard Time',
        utc: 'UTC-06:00',
        mobileCode: '+504',
    },
    {
        text: 'Hong Kong SAR',
        value: 'HK',
        timezone: 'China Standard Time',
        utc: 'UTC+08:00',
        mobileCode: '+852',
    },
    {
        text: 'Hungary',
        value: 'HU',
        timezone: 'Central Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+36',
    },
    {
        text: 'Iceland',
        value: 'IS',
        timezone: 'Greenwich Standard Time',
        utc: 'UTC',
        mobileCode: '+354',
    },
    {
        text: 'India',
        value: 'IN',
        timezone: 'India Standard Time',
        utc: 'UTC+05:30',
        mobileCode: '+91',
    },
    {
        text: 'Indonesia',
        value: 'ID',
        timezone: 'SE Asia Standard Time',
        utc: 'UTC+07:00',
        mobileCode: '+62',
    },
    {
        text: 'Iran',
        value: 'IR',
        timezone: 'Iran Standard Time',
        utc: 'UTC+03:30',
        mobileCode: '+98',
    },
    {
        text: 'Iraq',
        value: 'IQ',
        timezone: 'Arabic Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+964',
    },
    {
        text: 'Ireland',
        value: 'IE',
        timezone: 'GMT Standard Time',
        utc: 'UTC',
        mobileCode: '+353',
    },
    {
        text: 'Israel',
        value: 'IL',
        timezone: 'Israel Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+972',
    },
    {
        text: 'Italy',
        value: 'IT',
        timezone: 'W. Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+39',
    },
    {
        text: 'Jamaica',
        value: 'JM',
        timezone: 'SA Pacific Standard Time',
        utc: 'UTC-05:00',
        mobileCode: '+1-876',
    },
    {
        text: 'Jan Mayen',
        value: 'SJ',
        timezone: 'W. Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+47',
    },
    {
        text: 'Japan',
        value: 'JP',
        timezone: 'Tokyo Standard Time',
        utc: 'UTC+09:00',
        mobileCode: '+81',
    },
    {
        text: 'Jersey',
        value: 'JE',
        timezone: 'GMT Standard Time',
        utc: 'UTC',
        mobileCode: '+44-1534',
    },
    {
        text: 'Jordan',
        value: 'JO',
        timezone: 'Jordan Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+962',
    },
    {
        text: 'Kazakhstan',
        value: 'KZ',
        timezone: 'Central Asia Standard Time',
        utc: 'UTC+06:00',
        mobileCode: '+7',
    },
    {
        text: 'Kenya',
        value: 'KE',
        timezone: 'E. Africa Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+254',
    },
    {
        text: 'Kiribati',
        value: 'KI',
        timezone: 'UTC+12',
        utc: 'UTC+12:00',
        mobileCode: '+686',
    },
    {
        text: 'Korea',
        value: 'KR',
        timezone: 'Korea Standard Time',
        utc: 'UTC+09:00',
        mobileCode: '+82',
    },
    {
        text: 'Kosovo',
        value: 'XK',
        timezone: 'Central European Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+',
    },
    {
        text: 'Kuwait',
        value: 'KW',
        timezone: 'Arab Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+965',
    },
    {
        text: 'Kyrgyzstan',
        value: 'KG',
        timezone: 'Central Asia Standard Time',
        utc: 'UTC+06:00',
        mobileCode: '+996',
    },
    {
        text: 'Laos',
        value: 'LA',
        timezone: 'SE Asia Standard Time',
        utc: 'UTC+07:00',
        mobileCode: '+856',
    },
    {
        text: 'Latvia',
        value: 'LV',
        timezone: 'FLE Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+371',
    },
    {
        text: 'Lebanon',
        value: 'LB',
        timezone: 'Middle East Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+961',
    },
    {
        text: 'Lesotho',
        value: 'LS',
        timezone: 'South Africa Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+266',
    },
    {
        text: 'Liberia',
        value: 'LR',
        timezone: 'Greenwich Standard Time',
        utc: 'UTC',
        mobileCode: '+231',
    },
    {
        text: 'Libya',
        value: 'LY',
        timezone: 'E. Europe Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+218',
    },
    {
        text: 'Liechtenstein',
        value: 'LI',
        timezone: 'W. Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+423',
    },
    {
        text: 'Lithuania',
        value: 'LT',
        timezone: 'FLE Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+370',
    },
    {
        text: 'Luxembourg',
        value: 'LU',
        timezone: 'W. Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+352',
    },
    {
        text: 'Macao SAR',
        value: 'MO',
        timezone: 'China Standard Time',
        utc: 'UTC+08:00',
        mobileCode: '+853',
    },
    {
        text: 'Macedonia, Former Yugoslav Republic of',
        value: 'MK',
        timezone: 'Central European Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+389',
    },
    {
        text: 'Madagascar',
        value: 'MG',
        timezone: 'E. Africa Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+261',
    },
    {
        text: 'Malawi',
        value: 'MW',
        timezone: 'South Africa Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+265',
    },
    {
        text: 'Malaysia',
        value: 'MY',
        timezone: 'Singapore Standard Time',
        utc: 'UTC+08:00',
        mobileCode: '+60',
    },
    {
        text: 'Maldives',
        value: 'MV',
        timezone: 'West Asia Standard Time',
        utc: 'UTC+05:00',
        mobileCode: '+960',
    },
    {
        text: 'Mali',
        value: 'ML',
        timezone: 'Greenwich Standard Time',
        utc: 'UTC',
        mobileCode: '+223',
    },
    {
        text: 'Malta',
        value: 'MT',
        timezone: 'W. Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+356',
    },
    {
        text: 'Man, Isle of',
        value: 'IM',
        timezone: 'GMT Standard Time',
        utc: 'UTC',
        mobileCode: '+44-1624',
    },
    {
        text: 'Marshall Islands',
        value: 'MH',
        timezone: 'UTC+12',
        utc: 'UTC+12:00',
        mobileCode: '+692',
    },
    {
        text: 'Martinique',
        value: 'MQ',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+596',
    },
    {
        text: 'Mauritania',
        value: 'MR',
        timezone: 'Greenwich Standard Time',
        utc: 'UTC',
        mobileCode: '+222',
    },
    {
        text: 'Mauritius',
        value: 'MU',
        timezone: 'Mauritius Standard Time',
        utc: 'UTC+04:00',
        mobileCode: '+230',
    },
    {
        text: 'Mayotte',
        value: 'YT',
        timezone: 'E. Africa Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+262',
    },
    {
        text: 'Mexico',
        value: 'MX',
        timezone: 'Central Standard Time (Mexico)',
        utc: 'UTC-06:00',
        mobileCode: '+52',
    },
    {
        text: 'Micronesia',
        value: 'FM',
        timezone: 'West Pacific Standard Time',
        utc: 'UTC+10:00',
        mobileCode: '+691',
    },
    {
        text: 'Moldova',
        value: 'MD',
        timezone: 'GTB Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+373',
    },
    {
        text: 'Monaco',
        value: 'MC',
        timezone: 'W. Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+377',
    },
    {
        text: 'Mongolia',
        value: 'MN',
        timezone: 'Ulaanbaatar Standard Time',
        utc: 'UTC+08:00',
        mobileCode: '+976',
    },
    {
        text: 'Montenegro',
        value: 'ME',
        timezone: 'Central European Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+382',
    },
    {
        text: 'Montserrat',
        value: 'MS',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+1-664',
    },
    {
        text: 'Morocco',
        value: 'MA',
        timezone: 'Morocco Standard Time',
        utc: 'UTC',
        mobileCode: '+212',
    },
    {
        text: 'Mozambique',
        value: 'MZ',
        timezone: 'South Africa Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+258',
    },
    {
        text: 'Myanmar',
        value: 'MM',
        timezone: 'Myanmar Standard Time',
        utc: 'UTC+06:30',
        mobileCode: '+95',
    },
    {
        text: 'Namibia',
        value: 'NA',
        timezone: 'Namibia Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+264',
    },
    {
        text: 'Nauru',
        value: 'NR',
        timezone: 'UTC+12',
        utc: 'UTC+12:00',
        mobileCode: '+674',
    },
    {
        text: 'Nepal',
        value: 'NP',
        timezone: 'Nepal Standard Time',
        utc: 'UTC+05:45',
        mobileCode: '+977',
    },
    {
        text: 'Netherlands',
        value: 'NL',
        timezone: 'W. Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+31',
    },
    {
        text: 'New Caledonia',
        value: 'NC',
        timezone: 'Central Pacific Standard Time',
        utc: 'UTC+11:00',
        mobileCode: '+687',
    },
    {
        text: 'New Zealand',
        value: 'NZ',
        timezone: 'New Zealand Standard Time',
        utc: 'UTC+12:00',
        mobileCode: '+64',
    },
    {
        text: 'Nicaragua',
        value: 'NI',
        timezone: 'Central America Standard Time',
        utc: 'UTC-06:00',
        mobileCode: '+505',
    },
    {
        text: 'Niger',
        value: 'NE',
        timezone: 'W. Central Africa Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+227',
    },
    {
        text: 'Nigeria',
        value: 'NG',
        timezone: 'W. Central Africa Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+234',
    },
    {
        text: 'Niue',
        value: 'NU',
        timezone: 'UTC-11',
        utc: 'UTC-11:00',
        mobileCode: '+683',
    },
    {
        text: 'Norfolk Island',
        value: 'NF',
        timezone: 'Central Pacific Standard Time',
        utc: 'UTC+11:00',
        mobileCode: '+672',
    },
    {
        text: 'North Korea',
        value: 'KP',
        timezone: 'Korea Standard Time',
        utc: 'UTC+09:00',
        mobileCode: '+850',
    },
    {
        text: 'Northern Mariana Islands',
        value: 'MP',
        timezone: 'West Pacific Standard Time',
        utc: 'UTC+10:00',
        mobileCode: '+1-670',
    },
    {
        text: 'Norway',
        value: 'NO',
        timezone: 'W. Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+47',
    },
    {
        text: 'Oman',
        value: 'OM',
        timezone: 'Arabian Standard Time',
        utc: 'UTC+04:00',
        mobileCode: '+968',
    },
    {
        text: 'Pakistan',
        value: 'PK',
        timezone: 'Pakistan Standard Time',
        utc: 'UTC+05:00',
        mobileCode: '+92',
    },
    {
        text: 'Palau',
        value: 'PW',
        timezone: 'Tokyo Standard Time',
        utc: 'UTC+09:00',
        mobileCode: '+680',
    },
    {
        text: 'Palestinian Authority',
        value: 'PS',
        timezone: 'Egypt Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+970',
    },
    {
        text: 'Panama',
        value: 'PA',
        timezone: 'SA Pacific Standard Time',
        utc: 'UTC-05:00',
        mobileCode: '+507',
    },
    {
        text: 'Papua New Guinea',
        value: 'PG',
        timezone: 'West Pacific Standard Time',
        utc: 'UTC+10:00',
        mobileCode: '+675',
    },
    {
        text: 'Paraguay',
        value: 'PY',
        timezone: 'Paraguay Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+595',
    },
    {
        text: 'Peru',
        value: 'PE',
        timezone: 'SA Pacific Standard Time',
        utc: 'UTC-05:00',
        mobileCode: '+51',
    },
    {
        text: 'Philippines',
        value: 'PH',
        timezone: 'Singapore Standard Time',
        utc: 'UTC+08:00',
        mobileCode: '+63',
    },
    {
        text: 'Pitcairn Islands',
        value: 'PN',
        timezone: 'Pacific Standard Time',
        utc: 'UTC-08:00',
        mobileCode: '+870',
    },
    {
        text: 'Poland',
        value: 'PL',
        timezone: 'Central European Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+48',
    },
    {
        text: 'Portugal',
        value: 'PT',
        timezone: 'GMT Standard Time',
        utc: 'UTC',
        mobileCode: '+351',
    },
    {
        text: 'Puerto Rico',
        value: 'PR',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+1-787 and 1-939',
    },
    {
        text: 'Qatar',
        value: 'QA',
        timezone: 'Arab Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+974',
    },
    {
        text: 'Reunion',
        value: 'RE',
        timezone: 'Mauritius Standard Time',
        utc: 'UTC+04:00',
        mobileCode: '+262',
    },
    {
        text: 'Romania',
        value: 'RO',
        timezone: 'GTB Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+40',
    },
    {
        text: 'Russia',
        value: 'RU',
        timezone: 'Russian Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+7',
    },
    {
        text: 'Rwanda',
        value: 'RW',
        timezone: 'South Africa Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+250',
    },
    {
        text: 'Saint Barthélemy',
        value: 'BL',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+590',
    },
    {
        text: 'Saint Helena, Ascension and Tristan da Cunha',
        value: 'SH',
        timezone: 'Greenwich Standard Time',
        utc: 'UTC',
        mobileCode: '+290',
    },
    {
        text: 'Saint Kitts and Nevis',
        value: 'KN',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+1-869',
    },
    {
        text: 'Saint Lucia',
        value: 'LC',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+1-758',
    },
    {
        text: 'Saint Martin (French part)',
        value: 'MF',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+590',
    },
    {
        text: 'Saint Pierre and Miquelon',
        value: 'PM',
        timezone: 'Greenland Standard Time',
        utc: 'UTC-03:00',
        mobileCode: '+508',
    },
    {
        text: 'Saint Vincent and the Grenadines',
        value: 'VC',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+1-784',
    },
    {
        text: 'Samoa',
        value: 'WS',
        timezone: 'Samoa Standard Time',
        utc: 'UTC+13:00',
        mobileCode: '+685',
    },
    {
        text: 'San Marino',
        value: 'SM',
        timezone: 'W. Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+378',
    },
    {
        text: 'São Tomé and Príncipe',
        value: 'ST',
        timezone: 'Greenwich Standard Time',
        utc: 'UTC',
        mobileCode: '+239',
    },
    {
        text: 'Saudi Arabia',
        value: 'SA',
        timezone: 'Arab Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+966',
    },
    {
        text: 'Senegal',
        value: 'SN',
        timezone: 'Greenwich Standard Time',
        utc: 'UTC',
        mobileCode: '+221',
    },
    {
        text: 'Serbia',
        value: 'RS',
        timezone: 'Central Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+381',
    },
    {
        text: 'Seychelles',
        value: 'SC',
        timezone: 'Mauritius Standard Time',
        utc: 'UTC+04:00',
        mobileCode: '+248',
    },
    {
        text: 'Sierra Leone',
        value: 'SL',
        timezone: 'Greenwich Standard Time',
        utc: 'UTC',
        mobileCode: '+232',
    },
    {
        text: 'Singapore',
        value: 'SG',
        timezone: 'Singapore Standard Time',
        utc: 'UTC+08:00',
        mobileCode: '+65',
    },
    {
        text: 'Sint Maarten (Dutch part)',
        value: 'SX',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+599',
    },
    {
        text: 'Slovakia',
        value: 'SK',
        timezone: 'Central Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+421',
    },
    {
        text: 'Slovenia',
        value: 'SI',
        timezone: 'Central Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+386',
    },
    {
        text: 'Solomon Islands',
        value: 'SB',
        timezone: 'Central Pacific Standard Time',
        utc: 'UTC+11:00',
        mobileCode: '+677',
    },
    {
        text: 'Somalia',
        value: 'SO',
        timezone: 'E. Africa Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+252',
    },
    {
        text: 'South Africa',
        value: 'ZA',
        timezone: 'South Africa Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+27',
    },
    {
        text: 'South Georgia and the South Sandwich Islands',
        value: 'GS',
        timezone: 'UTC-02',
        utc: 'UTC-02:00',
        mobileCode: '+',
    },
    {
        text: 'South Sudan',
        value: 'SS',
        timezone: 'E. Africa Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+211',
    },
    {
        text: 'Spain',
        value: 'ES',
        timezone: 'Romance Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+34',
    },
    {
        text: 'Sri Lanka',
        value: 'LK',
        timezone: 'Sri Lanka Standard Time',
        utc: 'UTC+05:30',
        mobileCode: '+94',
    },
    {
        text: 'Sudan',
        value: 'SD',
        timezone: 'E. Africa Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+249',
    },
    {
        text: 'Suritext',
        value: 'SR',
        timezone: 'SA Eastern Standard Time',
        utc: 'UTC-03:00',
        mobileCode: '+597',
    },
    {
        text: 'Svalbard',
        value: 'SJ',
        timezone: 'W. Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+47',
    },
    {
        text: 'Swaziland',
        value: 'SZ',
        timezone: 'South Africa Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+268',
    },
    {
        text: 'Sweden',
        value: 'SE',
        timezone: 'W. Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+46',
    },
    {
        text: 'Switzerland',
        value: 'CH',
        timezone: 'W. Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+41',
    },
    {
        text: 'Syria',
        value: 'SY',
        timezone: 'Syria Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+963',
    },
    {
        text: 'Taiwan',
        value: 'TW',
        timezone: 'Taipei Standard Time',
        utc: 'UTC+08:00',
        mobileCode: '+886',
    },
    {
        text: 'Tajikistan',
        value: 'TJ',
        timezone: 'West Asia Standard Time',
        utc: 'UTC+05:00',
        mobileCode: '+992',
    },
    {
        text: 'Tanzania',
        value: 'TZ',
        timezone: 'E. Africa Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+255',
    },
    {
        text: 'Thailand',
        value: 'TH',
        timezone: 'SE Asia Standard Time',
        utc: 'UTC+07:00',
        mobileCode: '+66',
    },
    {
        text: 'Togo',
        value: 'TG',
        timezone: 'Greenwich Standard Time',
        utc: 'UTC',
        mobileCode: '+228',
    },
    {
        text: 'Tokelau',
        value: 'TK',
        timezone: 'Tonga Standard Time',
        utc: 'UTC+13:00',
        mobileCode: '+690',
    },
    {
        text: 'Tonga',
        value: 'TO',
        timezone: 'Tonga Standard Time',
        utc: 'UTC+13:00',
        mobileCode: '+676',
    },
    {
        text: 'Trinidad and Tobago',
        value: 'TT',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+1-868',
    },
    {
        text: 'Tunisia',
        value: 'TN',
        timezone: 'W. Central Africa Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+216',
    },
    {
        text: 'Turkey',
        value: 'TR',
        timezone: 'Turkey Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+90',
    },
    {
        text: 'Turkmenistan',
        value: 'TM',
        timezone: 'West Asia Standard Time',
        utc: 'UTC+05:00',
        mobileCode: '+993',
    },
    {
        text: 'Turks and Caicos Islands',
        value: 'TC',
        timezone: 'Eastern Standard Time',
        utc: 'UTC-05:00',
        mobileCode: '+1-649',
    },
    {
        text: 'Tuvalu',
        value: 'TV',
        timezone: 'UTC+12',
        utc: 'UTC+12:00',
        mobileCode: '+688',
    },
    {
        text: 'U.S. Minor Outlying Islands',
        value: 'UM',
        timezone: 'UTC-11',
        utc: 'UTC-11:00',
        mobileCode: '+1',
    },
    {
        text: 'Uganda',
        value: 'UG',
        timezone: 'E. Africa Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+256',
    },
    {
        text: 'Ukraine',
        value: 'UA',
        timezone: 'FLE Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+380',
    },
    {
        text: 'United Arab Emirates',
        value: 'AE',
        timezone: 'Arabian Standard Time',
        utc: 'UTC+04:00',
        mobileCode: '+971',
    },
    {
        text: 'United Kingdom',
        value: 'GB',
        timezone: 'GMT Standard Time',
        utc: 'UTC',
        mobileCode: '+44',
    },
    {
        text: 'United States',
        value: 'US',
        timezone: 'Pacific Standard Time',
        utc: 'UTC-08:00',
        mobileCode: '+1',
    },
    {
        text: 'Uruguay',
        value: 'UY',
        timezone: 'Montevideo Standard Time',
        utc: 'UTC-03:00',
        mobileCode: '+598',
    },
    {
        text: 'Uzbekistan',
        value: 'UZ',
        timezone: 'West Asia Standard Time',
        utc: 'UTC+05:00',
        mobileCode: '+998',
    },
    {
        text: 'Vanuatu',
        value: 'VU',
        timezone: 'Central Pacific Standard Time',
        utc: 'UTC+11:00',
        mobileCode: '+678',
    },
    {
        text: 'Vatican City',
        value: 'VA',
        timezone: 'W. Europe Standard Time',
        utc: 'UTC+01:00',
        mobileCode: '+379',
    },
    {
        text: 'Vietnam',
        value: 'VN',
        timezone: 'SE Asia Standard Time',
        utc: 'UTC+07:00',
        mobileCode: '+84',
    },
    {
        text: 'Virgin Islands, U.S.',
        value: 'VI',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+1-340',
    },
    {
        text: 'Virgin Islands, British',
        value: 'VG',
        timezone: 'SA Western Standard Time',
        utc: 'UTC-04:00',
        mobileCode: '+1-284',
    },
    {
        text: 'Wallis and Futuna',
        value: 'WF',
        timezone: 'UTC+12',
        utc: 'UTC+12:00',
        mobileCode: '+681',
    },
    {
        text: 'Yemen',
        value: 'YE',
        timezone: 'Arab Standard Time',
        utc: 'UTC+03:00',
        mobileCode: '+967',
    },
    {
        text: 'Zambia',
        value: 'ZM',
        timezone: 'South Africa Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+260',
    },
    {
        text: 'Zimbabwe',
        value: 'ZW',
        timezone: 'South Africa Standard Time',
        utc: 'UTC+02:00',
        mobileCode: '+263',
    },
];

export const dashboardData = {
    project_grid_XL: 'Project Grid [XL] ',
    project_grid_Large: 'Project Grid [Large] ',
    project_task: 'Project Task ',
    project_status: 'Project Status Graph',
    project_grid_small: 'Project Grid [Small]',
    project_budget_grid: 'Project Budget Grid',
    project_subtask: 'Project Subtask',
    project_by_status: 'Project Status',
    project_stage_grid: 'Project Stage',
    project_recent: 'Recent Projects',
    project_member_grid: 'Project Memmbers',
    project_progress: 'Project Progress',
    task_grid_XL: 'Task Grid [XL] ',
    task_grid_Large: 'Task Grid [Large] ',
    task_grid_small: 'Task Grid [Small]',
    task_status: 'Task Status',
    task_subtasks: 'Task Subtasks',
    task_priority: 'Task Priority',
    task_recent: 'Task Recent',
    task_member_grid: 'Task Members',
    task_progress: 'Task Progress',
    task_type: 'Task Type',
    task_category: 'Task Category',
    subtask_grid_XL: 'Subtask Grid [XL]',
    subtask_grid_Large: 'Subtask Grid [Large]',
    subtask_grid_small: 'Subtask Grid [Small]',
    subtask_status: 'Subtask Status Graph',
    subtask_recent: 'Subtask Recent',
    subtask_member_grid: 'Subtask Members',
    subtask_progress: 'Subtask Progress',
    subtask_priority: 'Subtask Priority',
    subtask_type: 'Subtask Type',
    subtask_category: 'Subtask Category',
    status: 'Subtask Status',
    roles_grid: 'Role Grid',
    project_roles_grid: 'Project Roles Grid',
    task_roles_grid: 'Task Roles Grid',
    subtask_roles_grid: 'Subtask Roles Grid',
    member_roles_grid: 'Member Roles Grid',
    custom_roles_grid: 'Custom Roles Grid',
    roles_progress_grid: 'Roles Progress Grid',
    member_grid_XL: 'Member Grid [XL]',
    member_grid_Large: 'Member Grid [Large]',
    member_grid_small: 'Member Grid [Small]',
    project_members_grid: 'Project Members Grid',
    task_members_grid: 'Task Members Grid',
    subtask_members_grid: 'Subtask Members Grid',
    roles_member_grid: 'Roles Member Grid',
    role_wise_members: 'Rol Wise Members',
    permission_members_grid: 'Permission Mmebers Grid',
    members_progress_grid: 'Members Progress Grid',
    permission_grid: 'Permission Grid',
    project_permission_grid: 'Project Permission Grid',
    task_permission_grid: 'Task Permission Grid',
    subtask_permission_grid: 'Subtask Permission Grid',
    member_permission_grid: 'Member Permission Grid',
    custom_permission_grid: 'Custom Permission Grid',
    permission_progress_grid: 'Permission Progress Grid',
    activity_grid: 'Activity Grid',
    project_Activity_grid: 'Project Activity Grid',
    task_activity_grid: 'Task Activity Grid',
    subtask_activity_grid: 'Subtask Activity Grid',
    activity_progress_grid: 'Activity Progress Grid',
    activity_Main_categories_grid: 'Activity Main Category Grid',
    activity_filter: 'Activity Filter',
    comments_grid: 'Comments Grid',
    project_comments_grid: 'Project Comments Grid',
    task_comments_grid: 'Task Comments Grid',
    subtask_comments_grid: 'Subtask Comments Grid',
    member_comments_grid: 'Member Comments Grid',
    comments_progress_grid: 'Comments Progress Grid',
    files_grid: 'Files Grid',
    categories_files: 'Categories Files',
    project_files_grid: 'Project Files Grid',
    task_files_grid: 'Task Files Grid',
    subtask_files_grid: 'Subtask Files Grid',
    links_grid: 'Links Grid',
    project_links_grid: 'Project Links Grid',
    task_links_grid: 'Task Links Grid',
    subtask_links_grid: 'Subtask Links Grid',
    members_links_grid: 'Members Links Grid',
};
