import mongoose from 'mongoose';

let planSchema = new mongoose.Schema({
    planName: { type: String, required: true },
    planPrice: { type: Number, get: v => (v / 100).toFixed(2), set: v => v * 100 },
    isPlanActive: { type: Boolean },
    projectFeatureCount: { type: Number },
    taskFeatureCount: { type: Number },
    TimelineManagement: {type:Boolean},
    userFeatureCount: { type: Number },
    groupFeatureCount: { type: Number },
    subTaskFeatureCount: { type: Number },
    customizeRoles: { type: Number },
    customizePermission: { type: Number },
    customizeTaskType: { type: Number },
    customizeTaskStage: { type: Number },
    customizeTaskStatus: { type: Number },
    customizeSubTaskType: { type: Number },
    customizeSubTaskStatus: { type: Number },
    categoriesCount: { type: Number },
    currencyType: { type: String },
    currencyLogo: { type: String },
    durationType: { type: String },
    durationValue: { type: Number },
    expireDate: { type: Date },
    createdAt: { type: Date, default: Date.now() },
    updatedAt: { type: Date, default: Date.now() },
});
let planModel = mongoose.model('planSchema', planSchema);
export default planModel;

export let plans = [
    {
        planId: 1,
        planName: 'Free',
        planPrice: 100.0,
        projectFeatureCount: 1,
        taskFeatureCount: 20,
        userFeatureCount: 2,
        groupFeatureCount: 0,
        subTaskFeatureCount: 10,
        TimelineManagement: false,
        customizeRoles: 2,
        customizePermission: 2,
        customizeTaskType: 0,
        customizeTaskStage: 0,
        customizeTaskStatus: 0,
        customizeSubTaskType: 0,
        customizeSubTaskStatus: 0,
        categoriesCount: 0,
        currencyType: 'INR',
        currencyLogo: '₹',
        durationType: 'DAY',
        durationValue: 60,
    },
    {
        planId: 6,
        planName: 'basic',
        planPrice: 0,
        projectFeatureCount: 50,
        taskFeatureCount: 5000,
        userFeatureCount: 500,
        groupFeatureCount: 20,
        subTaskFeatureCount: 5000,
        TimelineManagement: true,
        customizeRoles: 50,
        customizePermission: 50,
        customizeTaskType: 10,
        customizeTaskStage: 10,
        customizeTaskStatus: 10,
        customizeSubTaskType: 10,
        customizeSubTaskStatus: 10,
        categoriesCount: 10,
        currencyType: 'INR',
        currencyLogo: '₹',
        durationType: 'YEAR',
        durationValue: 1,
    },
    {
        planId: 2,
        planName: 'Standard',
        planPrice: 500.0,
        projectFeatureCount: 5,
        taskFeatureCount: 100,
        userFeatureCount: 15,
        groupFeatureCount: 3,
        subTaskFeatureCount: 100,
        TimelineManagement: false,
        customizeRoles: 5,
        customizePermission: 5,
        customizeTaskType: 3,
        customizeTaskStage: 3,
        customizeTaskStatus: 3,
        customizeSubTaskType: 3,
        customizeSubTaskStatus: 3,
        categoriesCount: 3,
        currencyType: 'INR',
        currencyLogo: '₹',
        durationType: 'MONTH',
        durationValue: 1,
    },
    {
        planId: 3,
        planName: 'Premium',
        planPrice: 1000.0,
        projectFeatureCount: 10,
        taskFeatureCount: 300,
        userFeatureCount: 100,
        groupFeatureCount: 5,
        subTaskFeatureCount: 300,
        TimelineManagement: true,
        customizeRoles: 20,
        customizePermission: 20,
        customizeTaskType: 5,
        customizeTaskStage: 5,
        customizeTaskStatus: 5,
        customizeSubTaskType: 5,
        customizeSubTaskStatus: 5,
        categoriesCount: 2,
        currencyType: 'INR',
        currencyLogo: '₹',
        durationType: 'YEAR',
        durationValue: 1,
    },
    {
        planId: 4,
        planName: 'Pro',
        planPrice: 1000.0,
        projectFeatureCount: 15,
        taskFeatureCount: 500,
        userFeatureCount: 100,
        groupFeatureCount: 10,
        subTaskFeatureCount: 500,
        TimelineManagement: true,
        customizeRoles: 50,
        customizePermission: 50,
        customizeTaskType: 10,
        customizeTaskStage: 10,
        customizeTaskStatus: 10,
        customizeSubTaskType: 10,
        customizeSubTaskStatus: 10,
        categoriesCount: 2,
        currencyType: 'INR',
        currencyLogo: '₹',
        durationType: 'YEAR',
        durationValue: 1,
    },
    {
        planId: 5,
        planName: 'Enterprise',
        planPrice: 1000.0,
        projectFeatureCount: '25',
        taskFeatureCount: 5000,
        userFeatureCount: 100,
        groupFeatureCount: 20,
        subTaskFeatureCount: 7000,
        TimelineManagement: true,
        customizeRoles: 5,
        customizePermission: 4,
        customizeTaskType: 3,
        customizeTaskStage: 2,
        customizeTaskStatus: 3,
        customizeSubTaskType: 3,
        customizeSubTaskStatus: 3,
        categoriesCount: 2,
        currencyType: 'INR',
        currencyLogo: '₹',
        durationType: 'YEAR',
        durationValue: 1,
    }
];
