import mongoose from 'mongoose';
const projectFieldsSchema = new mongoose.Schema(
    {
        projectFields: [
            {
                stringInput_64: { type: Number },
                stringInput_256: { type: Number },
                stringInput_1000: { type: Number },
                date_dd_mm_yyyy: { type: Number },
                date_mm_dd_yyyy: { type: Number },
                date_dd_mm_yyyy: { type: Number },
                date_dd_mon_yyyy: { type: Number },
                date_yy_mon_dd: { type: Number },
                dateTime_ddmmyyyy_hhmmss: { type: Number },
                dateTime_mmddyyyy_hhmmss: { type: Number },
                dateTime_yyyymmdd_hhmmss: { type: Number },
                dateTime_ddmonyyyy_hhmmss: { type: Number },
                dateTime_yymondd_hhmmss: { type: Number },
                dateTime_ddmmyyyy_hhmm: { type: Number },
                dateTime_mmddyyyy_hhmm: { type: Number },
                dateTime_yyyymmdd_hhmm: { type: Number },
                dateTime_ddmonyyyy_hhmm: { type: Number },
                numberInput_6: { type: Number },
                numberInput_10: { type: Number },
                checkBox: { type: Number },
                labels: { type: Number },
                url: { type: Number },
                priority: { type: Number },
            },
        ],
        taskFields: [
            {
                stringInput_64: { type: Number },
                stringInput_256: { type: Number },
                stringInput_1000: { type: Number },
                date_dd_mm_yyyy: { type: Number },
                date_mm_dd_yyyy: { type: Number },
                date_dd_mm_yyyy: { type: Number },
                date_dd_mon_yyyy: { type: Number },
                date_yy_mon_dd: { type: Number },
                dateTime_ddmmyyyy_hhmmss: { type: Number },
                dateTime_mmddyyyy_hhmmss: { type: Number },
                dateTime_yyyymmdd_hhmmss: { type: Number },
                dateTime_ddmonyyyy_hhmmss: { type: Number },
                dateTime_yymondd_hhmmss: { type: Number },
                dateTime_ddmmyyyy_hhmm: { type: Number },
                dateTime_mmddyyyy_hhmm: { type: Number },
                dateTime_yyyymmdd_hhmm: { type: Number },
                dateTime_ddmonyyyy_hhmm: { type: Number },
                numberInput_6: { type: Number },
                numberInput_10: { type: Number },
                checkBox: { type: Number },
                labels: { type: Number },
                url: { type: Number },
                priority: { type: Number },
            },
        ],
        subTaskFields: [
            {
                stringInput_64: { type: Number },
                stringInput_256: { type: Number },
                stringInput_1000: { type: Number },
                date_dd_mm_yyyy: { type: Number },
                date_mm_dd_yyyy: { type: Number },
                date_dd_mm_yyyy: { type: Number },
                date_dd_mon_yyyy: { type: Number },
                date_yy_mon_dd: { type: Number },
                dateTime_ddmmyyyy_hhmmss: { type: Number },
                dateTime_mmddyyyy_hhmmss: { type: Number },
                dateTime_yyyymmdd_hhmmss: { type: Number },
                dateTime_ddmonyyyy_hhmmss: { type: Number },
                dateTime_yymondd_hhmmss: { type: Number },
                dateTime_ddmmyyyy_hhmm: { type: Number },
                dateTime_mmddyyyy_hhmm: { type: Number },
                dateTime_yyyymmdd_hhmm: { type: Number },
                dateTime_ddmonyyyy_hhmm: { type: Number },
                numberInput_6: { type: Number },
                numberInput_10: { type: Number },
                checkBox: { type: Number },
                labels: { type: Number },
                url: { type: Number },
                priority: { type: Number },
            },
        ],
        userFields: [
            {
                stringInput_64: { type: Number },
                stringInput_256: { type: Number },
                stringInput_1000: { type: Number },
                date_dd_mm_yyyy: { type: Number },
                date_mm_dd_yyyy: { type: Number },
                date_dd_mm_yyyy: { type: Number },
                date_dd_mon_yyyy: { type: Number },
                date_yy_mon_dd: { type: Number },
                dateTime_ddmmyyyy_hhmmss: { type: Number },
                dateTime_mmddyyyy_hhmmss: { type: Number },
                dateTime_yyyymmdd_hhmmss: { type: Number },
                dateTime_ddmonyyyy_hhmmss: { type: Number },
                dateTime_yymondd_hhmmss: { type: Number },
                dateTime_ddmmyyyy_hhmm: { type: Number },
                dateTime_mmddyyyy_hhmm: { type: Number },
                dateTime_yyyymmdd_hhmm: { type: Number },
                dateTime_ddmonyyyy_hhmm: { type: Number },
                numberInput_6: { type: Number },
                numberInput_10: { type: Number },
                checkBox: { type: Number },
                labels: { type: Number },
                url: { type: Number },
            },
        ],

        orgId: { type: String, required: true },
    },
    { strict: false }
);

export const configFieldSchema = mongoose.model('configFieldSchema', projectFieldsSchema);

const projectViewFieldsSchema = new mongoose.Schema(
    {
        projectViewFields: [
            {
                projectName: { type: Number },
                actualBudget: { type: Number },
                actualHours: { type: Number },
                adminName: { type: Number },
                adminProfilePic: { type: Number },
                createdAt: { type: Number },
                updatedAt: { type: Number },
                currencyType: { type: Number },
                description: { type: Number },
                endDate: { type: Number },
                estimationDate: { type: Number },
                estimationTime: { type: Number },
                plannedBudget: { type: Number },
                projectCode: { type: Number },
                projectCreatedBy: { type: Number },
                projectLogo: { type: Number },
                userAssigned: { type: Number },
                remainingHours: { type: Number },
                status: { type: Number },
                progress: { type: Number },
                startDate: { type: Number },
                userAssigned: { type: Number },
                memberCount: { type: Number },
                taskCount: { type: Number },
                taskDetails: { type: Number },
                subTaskCount: { type: Number },
                subTaskDetails: { type: Number },
                stringInput_64: { type: Number },
                stringInput_256: { type: Number },
                stringInput_1000: { type: Number },
                date_dd_mm_yyyy: { type: Number },
                date_mm_dd_yyyy: { type: Number },
                date_yyyy_mm_dd: { type: Number },
                date_dd_mon_yyyy: { type: Number },
                date_yy_mon_dd: { type: Number },
                dateTime_ddmmyyyy_hhmmss: { type: Number },
                dateTime_mmddyyyy_hhmmss: { type: Number },
                dateTime_yyyymmdd_hhmmss: { type: Number },
                dateTime_ddmonyyyy_hhmmss: { type: Number },
                dateTime_yymondd_hhmmss: { type: Number },
                dateTime_ddmmyyyy_hhmm: { type: Number },
                dateTime_mmddyyyy_hhmm: { type: Number },
                dateTime_yyyymmdd_hhmm: { type: Number },
                dateTime_ddmonyyyy_hhmm: { type: Number },
                numberInput_6: { type: Number },
                numberInput_10: { type: Number },
                checkBox: { type: Number },
                labels: { type: Number },
                url: { type: Number },
                priority: { type: Number },
            },
        ],
        taskViewFields: [
            {
                projectId: { type: Number },
                projectName: { type: Number },
                taskTitle: { type: Number },
                stageName: { type: Number },
                taskType: { type: Number },
                category: { type: Number },
                taskCreator: { type: Number },
                taskStatus: { type: Number },
                taskDetails: { type: Number },
                dueDate: { type: Number },
                createdAt: { type: Number },
                updatedAt: { type: Number },
                estimationTime: { type: Number },
                estimationDate: { type: Number },
                actualHours: { type: Number },
                remainingHours: { type: Number },
                assignedTo: { type: Number },
                attachment: { type: Number },
                epicLink: { type: Number },
                project: { type: Number },
                subTasks: { type: Number },
                standAloneTask: { type: Number },
                stringInput_64: { type: Number },
                stringInput_256: { type: Number },
                stringInput_1000: { type: Number },
                date_dd_mm_yyyy: { type: Number },
                date_mm_dd_yyyy: { type: Number },
                date_dd_mm_yyyy: { type: Number },
                date_dd_mon_yyyy: { type: Number },
                date_yy_mon_dd: { type: Number },
                dateTime_ddmmyyyy_hhmmss: { type: Number },
                dateTime_mmddyyyy_hhmmss: { type: Number },
                dateTime_yyyymmdd_hhmmss: { type: Number },
                dateTime_ddmonyyyy_hhmmss: { type: Number },
                dateTime_yymondd_hhmmss: { type: Number },
                dateTime_ddmmyyyy_hhmm: { type: Number },
                dateTime_mmddyyyy_hhmm: { type: Number },
                dateTime_yyyymmdd_hhmm: { type: Number },
                dateTime_ddmonyyyy_hhmm: { type: Number },
                numberInput_6: { type: Number },
                numberInput_10: { type: Number },
                checkBox: { type: Number },
                labels: { type: Number },
                url: { type: Number },
                priority: { type: Number },
            },
        ],
        subTaskViewFields: [
            {
                projectName: { type: Number },
                projectId: { type: Number },
                taskId: { type: Number },
                subTaskStageName: { type: Number },
                subTaskCategory: { type: Number },
                subTaskTitle: { type: Number },
                subTaskType: { type: Number },
                subTaskDetails: { type: Number },
                dueDate: { type: Number },
                estimationDate: { type: Number },
                estimationTime: { type: Number },
                actualHours: { type: Number },
                remainingHours: { type: Number },
                attachment: { type: Number },
                epicLink: { type: Number },
                priority: { type: Number },
                subTaskStatus: { type: Number },
                progress: { type: Number },
                task: { type: Number },
                subTaskCreator: { type: Number },
                subTaskAssignedTo: { type: Number },
                createdAt: { type: Number },
                updatedAt: { type: Number },
                subTaskCreator: { type: Number },
                subTaskAssignedTo: { type: Number },
                stringInput_64: { type: Number },
                stringInput_256: { type: Number },
                stringInput_1000: { type: Number },
                date_dd_mm_yyyy: { type: Number },
                date_mm_dd_yyyy: { type: Number },
                date_dd_mm_yyyy: { type: Number },
                date_dd_mon_yyyy: { type: Number },
                date_yy_mon_dd: { type: Number },
                dateTime_ddmmyyyy_hhmmss: { type: Number },
                dateTime_mmddyyyy_hhmmss: { type: Number },
                dateTime_yyyymmdd_hhmmss: { type: Number },
                dateTime_ddmonyyyy_hhmmss: { type: Number },
                dateTime_yymondd_hhmmss: { type: Number },
                dateTime_ddmmyyyy_hhmm: { type: Number },
                dateTime_mmddyyyy_hhmm: { type: Number },
                dateTime_yyyymmdd_hhmm: { type: Number },
                dateTime_ddmonyyyy_hhmm: { type: Number },
                numberInput_6: { type: Number },
                numberInput_10: { type: Number },
                checkBox: { type: Number },
                labels: { type: Number },
                url: { type: Number },
                priority: { type: Number },
            },
        ],
        userViewFields: [
            {
                firstName: { type: Number },
                lastName: { type: Number },
                email: { type: Number },
                role: { type: Number },
                permission: { type: Number },
                profilePic: { type: Number },
                verified: { type: Number },
                verificationEmailSentCount: { type: Number },
                softDeleted: { type: Number },
                forgotPasswordToken: { type: Number },
                forgotTokenExpire: { type: Number },
                passwordEmailSentCount: { type: Number },
                orgId: { type: Number },
                adminId: { type: Number },
                password: { type: Number },
                Project_details: { type: Number },
                task_details: { type: Number },
                subTask_details: { type: Number },
                emailValidateToken: { type: Number },
                emailTokenExpire: { type: Number },
                isAdmin: { type: Number },
                invitation: {type: Number},
                createdAt: { type: Number },
                updatedAt: { type: Number },
                stringInput_64: { type: Number },
                stringInput_256: { type: Number },
                stringInput_1000: { type: Number },
                date_dd_mm_yyyy: { type: Number },
                date_mm_dd_yyyy: { type: Number },
                date_dd_mm_yyyy: { type: Number },
                date_dd_mon_yyyy: { type: Number },
                date_yy_mon_dd: { type: Number },
                dateTime_ddmmyyyy_hhmmss: { type: Number },
                dateTime_mmddyyyy_hhmmss: { type: Number },
                dateTime_yyyymmdd_hhmmss: { type: Number },
                dateTime_ddmonyyyy_hhmmss: { type: Number },
                dateTime_yymondd_hhmmss: { type: Number },
                dateTime_ddmmyyyy_hhmm: { type: Number },
                dateTime_mmddyyyy_hhmm: { type: Number },
                dateTime_yyyymmdd_hhmm: { type: Number },
                dateTime_ddmonyyyy_hhmm: { type: Number },
                numberInput_6: { type: Number },
                numberInput_10: { type: Number },
                checkBox: { type: Number },
                labels: { type: Number },
                url: { type: Number },
            },
        ],
        orgId: { type: String, required: true },
    },
    { strict: false }
);
export const configViewFieldSchema = mongoose.model('configViewFieldSchema', projectViewFieldsSchema);
const dynamicFields = new mongoose.Schema({
    createProjectField: 
        {
            fieldName: { type: String },
            type: { type: String, enum: ['number', 'string', 'date', 'boolean'] },
            conditions: {
                min: { type: Number },
                max: { type: Number },
                valid: { type: Number },
            },
            format: {type:String}
        },
        createTaskField: 
        {
            fieldName: { type: String },
            type: { type: String, enum: ['number', 'string', 'date', 'boolean'] },
            conditions: {
                min: { type: Number },
                max: { type: Number },
                valid: { type: Number },
            },
        },
        createSubTaskField: 
        {
            fieldName: { type: String },
            type: { type: String, enum: ['number', 'string', 'date', 'boolean'] },
            conditions: {
                min: { type: Number},
                max: { type: Number },
                valid: { type: Number },
            },
        },
    
    orgId: { type: String },
});
export const dynamicFieldSchema = mongoose.model('dynamicFieldSchema', dynamicFields);
